Rewritten java to kotlin
Innim/flutter_login_vk pull request #11
Opened 2021-09-27 11:10 UTC by baihu92

2021-09-27 15:31 UTC, greymag requested changes
Привет! Спасибо за отличный PR =) Пара вопросов/предложений

2021-09-27 15:31 UTC, greymag commented on android/src/main/kotlin/ru/innim/flutter_login_vk/VKClient.kt
> +        fun hasScopes(scopes: List<VKScope?>?, permission: Int): Boolean {
Может `List<VKScope>?`? Зачем нам `null` в списке?

2021-09-27 15:31 UTC, greymag commented on android/src/main/kotlin/ru/innim/flutter_login_vk/MethodCallHandler.kt
> +            val storage = VKPreferencesKeyValueStorage(context)
Этот `storage` точно будет совпадать с тем, что использует VK? Не потеряем мы токен?

2021-09-27 17:00 UTC, baihu92 commented on android/src/main/kotlin/ru/innim/flutter_login_vk/MethodCallHandler.kt
> +            val storage = VKPreferencesKeyValueStorage(context)
VK внутри использует sharedPreferences для хранения токенов. VKPreferencesKeyValueStorage, является его оберткой. По сути, мы обращаемся к тому-же  sharedPreferences, но через свой инстанс VKPreferencesKeyValueStorage. Сделал так, потому что адекватных альтернатив не нашел. (Не понимаю, почему VK не для андроида, не предоставляет метода получения токена). Проверял на своем проекте, каких-то проблем не выявил.

2021-09-27 17:08 UTC, baihu92 commented on android/src/main/kotlin/ru/innim/flutter_login_vk/VKClient.kt
> +        fun hasScopes(scopes: List<VKScope?>?, permission: Int): Boolean {
Согласен. Хотя в этом месте, вполне возможно использовать и такой вариант: 
`fun hasScopes(scopes: List<VKScope>, permission: Int): Boolean {`

2021-09-28 15:14 UTC, greymag approved these changes

2021-09-28 15:14 UTC, merged