Feature/update sdk
Innim/flutter_login_vk pull request #5
Opened 2021-09-07 12:36 UTC by mongugay

2021-09-08 14:10 UTC, greymag requested changes
Не забыть README обновить

2021-09-08 14:10 UTC, greymag commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +    static VKAccessToken TOKEN;
Статические нефинальные свойства так не именуются обычно. Но вообще лучше от него конечно избавиться бы совсем

2021-09-08 14:10 UTC, greymag commented on android/src/main/java/ru/innim/flutter_login_vk/LoginCallback.java
> +        VKClient.TOKEN = accessToken;
Ой, какой нехороший вариант. Там так рекомендуется делать? Нам вообще надо хранить самим токен, у них неоткуда получить чтоли? Ведь если сами храним, то и обновление самим надо отслеживать

2021-09-08 14:10 UTC, greymag commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +                bytes += SCOPE_BYTES.get(scope);
Ты маску сравниваешь, лучше не +, а побитовое или `|`

2021-09-08 14:10 UTC, greymag commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +            int bytes = 0;
Название говорящее дай

2021-09-08 14:10 UTC, greymag commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +            return permission == bytes;
Так ты получишь `true` только если точное совпадение, а если в  permissions больше разрешений чем нам надо, то будет `false`, не смотря на то, что все требуемые scopes есть

2021-09-08 14:10 UTC, greymag commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +    static boolean hasScope(List<VKScope> scopes, int permission) {
hasScopes?

2021-09-08 14:10 UTC, greymag commented on example/android/app/src/main/res/values/strings.xml
> +    <integer name="com_vk_sdk_AppId">7503887</integer>
А зачем изменил ID тестового приложения?

2021-09-08 14:10 UTC, greymag commented on ios/Classes/SwiftFlutterLoginVkPlugin.swift
> -                let appIdArg = args[InitSdkArg.appId.rawValue] as? String
Если этот параметр не используется - удали его из enum

2021-09-08 14:10 UTC, greymag commented on ios/Classes/SwiftFlutterLoginVkPlugin.swift
> -            let apiVersionArg = args[InitSdkArg.apiVersion.rawValue] as? String
Аналогично

2021-09-08 14:10 UTC, greymag commented on ios/Classes/SwiftFlutterLoginVkPlugin.swift
> +                    result(FlutterError.invalidArgs("App id is invalid"))
Скорее не invalid, а не задан - напиши более подробную ошибку, чтобы пользователь когда ее получил - понял что не так и что надо сделать

2021-09-08 14:10 UTC, greymag commented on ios/Classes/SwiftFlutterLoginVkPlugin.swift
> +                else{
пробел

2021-09-09 06:57 UTC, mongugay commented on ios/Classes/SwiftFlutterLoginVkPlugin.swift
> -            let apiVersionArg = args[InitSdkArg.apiVersion.rawValue] as? String
+

2021-09-09 06:57 UTC, mongugay commented on ios/Classes/SwiftFlutterLoginVkPlugin.swift
> -                let appIdArg = args[InitSdkArg.appId.rawValue] as? String
Поправил

2021-09-09 06:58 UTC, mongugay commented on ios/Classes/SwiftFlutterLoginVkPlugin.swift
> +                    result(FlutterError.invalidArgs("App id is invalid"))
Поправил

2021-09-09 06:58 UTC, mongugay commented on ios/Classes/SwiftFlutterLoginVkPlugin.swift
> +                else{
Поправил

2021-09-09 06:58 UTC, mongugay commented on example/android/app/src/main/res/values/strings.xml
> +    <integer name="com_vk_sdk_AppId">7503887</integer>
Правильный id от тестового приложения.

2021-09-09 07:23 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +    static boolean hasScope(List<VKScope> scopes, int permission) {
Поправил

2021-09-09 07:24 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +            return permission == bytes;
Поправил

2021-09-09 07:28 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +            int bytes = 0;
Поправил

2021-09-09 07:29 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/MethodCallHandler.java
> +    private final static String _GET_TOKEN_EXPIRED = "tokenExpired";
Убрал

2021-09-09 07:30 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/ActivityListener.java
> +        return !VK.onActivityResult(requestCode, resultCode, data, _loginCallback);
Опечатка

2021-09-09 08:22 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +    static VKAccessToken TOKEN;
Переименовал

2021-09-09 08:23 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/LoginCallback.java
> +        VKClient.TOKEN = accessToken;
Раньше мы могли его из sdk получить, но сейчас мы можем его только обнулить. Так что приходится его хранить ((

2021-09-09 11:22 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +                bytes += SCOPE_BYTES.get(scope);
Поправил

2021-09-09 11:31 UTC, mongugay commented on CHANGELOG.md
> +## 1.0.2 - 2021-09-07
Поправил

2021-09-09 11:41 UTC, mongugay commented on android/build.gradle
> +        minSdkVersion 21
Поправил

2021-09-09 11:41 UTC, mongugay commented on CHANGELOG.md
> +* [iOS] Change get app id.
Поправил

2021-09-10 06:50 UTC, greymag requested changes

2021-09-10 06:50 UTC, greymag commented on CHANGELOG.md
> +* **BREAKING** Method `initSdk()` does not accept `appId and apiVersion`.
```suggestion
* **BREAKING** Method `initSdk()` does not accept `appId` and `apiVersion`, you need to define it in `strings.xml`/`Info.plist`, see [README](./README.md).
```

2021-09-10 06:50 UTC, greymag commented on CHANGELOG.md
> +* **BREAKING** From `VKAccessToken` removed params `httpsRequired and expiresIn`.
```suggestion
* **BREAKING** Removed fields `httpsRequired ` and `expiresIn` from `VKAccessToken`.
```

2021-09-10 06:50 UTC, greymag commented on CHANGELOG.md
> +* [iOS] **BREAKING** Enter your VK application identifier in your Info.plist.
Лучше все написать в одном пункте - это общее изменение: изменился формат задания appId, см. suggestion к первому пункту. А отдельно этот и "[Android] **BREAKING** Add your VK application..." удали.

2021-09-10 06:50 UTC, greymag commented on README.md
> +* Android **4.1** and newer (SDK **21**).
SDK 21 это не 4.1 -  версию Android  забыл обновить

2021-09-10 06:50 UTC, greymag commented on README.md
> +3. Add your VK application identifier to the resource file (example strings.xml),
```suggestion
3. Add your VK application identifier to the resource file (e.g. `strings.xml`),
```

2021-09-10 06:50 UTC, greymag commented on android/src/main/java/ru/innim/flutter_login_vk/MethodCallHandler.java
> +    VKTokenExpiredHandler tokenExpiredHandler = new VKTokenExpiredHandler() {
Этот видимо не нужен, раз мы dart часть не оповещаем?

2021-09-10 06:50 UTC, greymag commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +            return permission >= sumBitmasks;
Неправильно, почему ты вообще тут делаешь операцию сравнения? Тебе вообще не нужна операция сравнения.

Ну и работает естественно неверно, самый банальный пример:
- permission  = FRIENDS (2)
- scopes = [NOTIFY] -> sumBitmasks = 1

2 > 1, т.е. функция вернет true, хотя требуемых прав не выдано

2021-09-10 06:50 UTC, greymag commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +        return false;
Так, а почему если scopes не задан или пуст (т.е. я ничего не требую), то ты возвращаешь false? По идее если я ничего не требую, то всегда есть все требуемые права (т.е. собственно я ничего не требую)

2021-09-10 06:50 UTC, greymag commented on ios/Classes/SwiftFlutterLoginVkPlugin.swift
> +                    result(FlutterError.invalidArgs("App id is not found. Please enter your VK application identifier in your Info.plist"))
```suggestion
                    result(FlutterError.invalidArgs("App ID is not found. Please add VKAppId parameter in Info.plist"))
```

2021-09-10 06:50 UTC, greymag commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +            int sumBitmasks = 0;
Название не подходящее - просто потому что это не сумма. Можно например `scopesMask`.

2021-09-10 06:54 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/LoginCallback.java
> +        VKClient.TOKEN = accessToken;
Удалил

2021-09-10 06:56 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +            int sumBitmasks = 0;
Изменил

2021-09-10 06:58 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/MethodCallHandler.java
> +    VKTokenExpiredHandler tokenExpiredHandler = new VKTokenExpiredHandler() {
Убрал

2021-09-10 07:02 UTC, mongugay commented on README.md
> +* Android **4.1** and newer (SDK **21**).
Поправил

2021-09-10 08:15 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +            return permission >= sumBitmasks;
Изменил

2021-09-10 08:15 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +        return false;
Изменил

2021-09-10 12:10 UTC, mongugay commented on CHANGELOG.md
> +* [iOS] **BREAKING** Enter your VK application identifier in your Info.plist.
Убрал

2021-09-10 12:22 UTC, greymag requested changes

2021-09-10 14:54 UTC, mongugay commented on android/src/main/java/ru/innim/flutter_login_vk/VKClient.java
> +    static final String SDK_VERSION = "3.2.2";
Убрал

2021-09-14 09:00 UTC, greymag approved these changes

2021-09-14 09:01 UTC, merged